title: Physical Robotic Manipulation Test Facility
description: Automated apparatuses for grasping data collection.
remote_theme: just-the-docs/just-the-docs@v0.5.4 # didn't have the version before
plugins:
  - jekyll-remote-theme
#url: https://osurobotics.github.io/Physical-Robotic-Manipulation-Test-Facility/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
color_scheme: dark


