title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs@v0.5.2

#url: https://osurobotics.github.io/Physical-Robotic-Manipulation-Test-Facility/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
